### PR TITLE
Bump tiny_http to 0.12

### PR DESCRIPTION
**Pull request by davide125**
Update the dependencies, build and tests pass as expected.

### CODE REVIEW

**Comment by neonmoe** [comment]
Is there a particular need for this? Especially since it's just for testing, I'd rather keep the version the same rather than mess with it just to keep the versions up to date.

**Comment by davide125** [comment]
Fedora has 0.12 (https://src.fedoraproject.org/rpms/rust-tiny_http) and would require a downstream patch to package `minreq` (as we only keep one version per crate in the distribution), so I figured it made sense to try and get this updated upstream.

**Comment by neonmoe** [comment]
Oh, that's understandable, no problem!

**Comment by neonmoe** [comment]
Thanks for the PR, hope this helps with the packaging!

**Pull request merged**
