### PR TITLE
http connect proxy support

### PR DESCRIPTION
**Pull request by rustysec**
I added support for http(s) proxies. Tested this with `tinyproxy` using unauthenticated and authenticated setups. Also added some documentation around it. Hopefully this is helpful.

If you want I could put it behind a `proxy` feature flag as well.

### CODE REVIEW

**Comment by neonmoe** [comment]
Seems like a useful thing to support, but I'd rather have it as a feature, so that would be appreciated. Thanks for the contribution! :+1:

**Comment by rustysec** [comment]
Should have done that in the beginning, let me know what you think.

**Comment by neonmoe** [comment]
Looking good! I'll do some minor tidying up and release a minor version update in just a sec :)

**Comment by rustysec** [comment]
Awesome, I would have done the tidying if you wanted to do a pr review.

**Pull request merged**
