### PR TITLE
added wasm target support

### PR DESCRIPTION
**Pull request by Mubelotix**
Minreq is now able to be used in a browser with wasm.
The native version has not changed at all thanks to conditional compilation.
The code is not pretty because of a lot of #[cfg] .
It should be possible to reorganize the code

### CODE REVIEW

**Comment by neonmoe** [comment]
Thank you very much! I'll look over the code tomorrow.

**Comment by neonmoe** [comment]
I'm sorry, but the changes are a bit too extensive for me to merge them right now. In addition to the amount of changes, reading the wasm implementation of send(), I feel like this code should be in application code, or a wasm-specific crate, rather than minreq.

Thank you again for your contribution, but as is, I won't merge it.

**Comment by Mubelotix** [comment]
What if we change the name of this crate to minreq-native, we create a crate named minreq-wasm with the exact same structure, and that we create a crate named minreq using the two first crates where all the cfg are located?

**Comment by neonmoe** [comment]
Too much of a maintenance burden for me, sorry. You can use the minreq name and code though, if you want to set up a `minreq-wasm` crate.

**Comment by Mubelotix** [comment]
Ok I will do it on a new crate. But I will not use the name "minreq" because that would not be the real minreq.

**Pull request closed without merging**
